version: '3.1'
services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./docker-data/db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: rootUser
      POSTGRES_USER: dev
      POSTGRES_DB: HIMS
    ports:
      - 5434:5432
  adminer:
    depends_on:
      - db
    image: adminer
    restart: always
    ports:
      - 4000:8080